import 'package:flutter/material.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedStrawberryicecreamWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedVeganbloggers01722x4061Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedDownload11Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedVeganCarrotCake41Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedVegancakeWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedFoodWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox4widget/generated/GeneratedVegancornflexWidget.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 97.0,
                child: GeneratedVeganCarrotCake41Widget(),
              ),
              Positioned(
                left: 279.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 97.0,
                child: GeneratedVeganbloggers01722x4061Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 118.0,
                child: GeneratedFoodWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 58.0,
                child: GeneratedVegancakeWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 51.0,
                child: GeneratedVegancornflexWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 277.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 97.0,
                child: GeneratedDownload11Widget(),
              ),
              Positioned(
                left: -3.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 44.0,
                child: GeneratedStrawberryicecreamWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 102.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 61.0,
                child: GeneratedBackWidget1(),
              )
            ]),
      ),
    ));
  }
}
