import 'package:flutter/material.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedWelcomebackBahjaWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/Generated1264722Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/Generated1264721Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedDd9dc9d83423bc037b511d73b29e6b801Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedDd9dc9d83423bc037b511d73b29e6b802Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedDownload1Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox2widget/generated/GeneratedDownload2Widget.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 267.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 25.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 267.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 24.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 267.0082092285156,
                top: 127.12549591064453,
                right: null,
                bottom: null,
                width: 93.0,
                height: 24.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 100.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 100.0,
                child: GeneratedDownload1Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 97.0,
                child: Generated1264721Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 97.0,
                child: GeneratedDd9dc9d83423bc037b511d73b29e6b801Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 100.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 100.0,
                child: GeneratedDownload2Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 97.0,
                child: Generated1264722Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 97.0,
                child: GeneratedDd9dc9d83423bc037b511d73b29e6b802Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 116.0,
                child: GeneratedWelcomebackBahjaWidget(),
              )
            ]),
      ),
    ));
  }
}
