import 'package:flutter/material.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedDd9dc9d83423bc037b511d73b29e6b802Widget1.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedFoodsWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedDownload2Widget1.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox3widget/generated/GeneratedRectangle6Widget.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 188.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 812.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 100.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 100.0,
                child: GeneratedDownload2Widget1(),
              ),
              Positioned(
                left: 137.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 97.0,
                child: GeneratedDd9dc9d83423bc037b511d73b29e6b802Widget1(),
              ),
              Positioned(
                left: 217.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 51.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 188.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 94.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 217.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 61.0,
                child: GeneratedFoodsWidget(),
              ),
              Positioned(
                left: 188.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 91.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 61.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 188.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 85.0,
                child: GeneratedRectangle6Widget(),
              )
            ]),
      ),
    ));
  }
}
