import 'package:flutter/material.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox1widget/generated/GeneratedImages1Widget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox1widget/generated/GeneratedWelcometotheVeganappWidget.dart';
import 'package:flutterapp/xpxapp/generatediphone11prox1widget/generated/GeneratedNextWidget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 114.0,
                child: GeneratedWelcometotheVeganappWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 225.0,
                child: GeneratedImages1Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 88.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 61.0,
                child: GeneratedNextWidget(),
              )
            ]),
      ),
    ));
  }
}
